#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

#zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

#-------------------------------------------------------------------------

MESSAGE=$(cat .git/hooks/commit_message.txt)
echo "Commit message: $MESSAGE"
#VERS=("sound" "1.8.9" "1.10.2" "1.12.2" "1.14.4" "1.16.1" "1.16.5" "1.17.1" "1.18.2" "1.19.2" "1.19.3" "1.19.4" "1.20.1" "1.20.2" "1.20.4" "1.20.6" "1.21.1" "1.21.3" "1.21.4" #"1.21.5" "test")

git submodule foreach '
  if [ -n "$(git status --porcelain)" ]; then
    echo "----$name----"
    git add .
    git commit -m "'"$MESSAGE"'"
    git push
    echo "-------------"
  fi
'
exit 0


for V in "${VERS[@]}"; do
	echo "----$V----"
	cd ".\resource\battlecats_$V"
	git add .
	git commit -m "$MESSAGE"
	git push
	cd ..
	cd ..
	echo ""
done

echo "-------------"

exit 0


#-------------------------------------------------------------------------

exit 0
